<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PropertyAdvertisementsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('property_advertisements')->delete();
        
        \DB::table('property_advertisements')->insert(array (
            0 => 
            array (
                'id' => 53,
                'city_id' => 1,
                'town_id' => 13,
                'sector_id' => 445,
                'block_id' => 870,
                'purpose' => 'Sale',
                'category' => 'Residential',
                'proptype' => 'Plot',
                'featured' => 1,
                'title' => 'Golden Urban house for Sell',
                'description' => 'Best Location',
                'address' => 'Main University Road Safoora',
                'latitude' => '24.9429278',
                'longitude' => '67.1591958',
                'area_size' => '240.00',
                'size_unit' => 'Sqf',
                'positioning' => 'East Open',
                'front_face' => 'Main Road',
                'back_site' => 'Playgound',
                'demand_price' => '12000.00',
                'pricetype' => 'Total Price',
                'housetype' => 'Single',
                'floor' => NULL,
                'bedrooms' => '3',
                'consage' => NULL,
                'conscond' => NULL,
                'postas' => 'Individual',
                'social' => 'Y',
                'user_id' => 1,
                'created_at' => '2025-10-02 00:00:36',
                'updated_at' => '2025-10-02 00:00:36',
            ),
            1 => 
            array (
                'id' => 54,
                'city_id' => 1,
                'town_id' => 13,
                'sector_id' => 17,
                'block_id' => 143,
                'purpose' => 'Rent',
                'category' => 'Residential',
                'proptype' => 'Plot',
                'featured' => 0,
                'title' => 'Golden Urban house for Rent',
                'description' => 'Good Location',
                'address' => 'Near Safoora',
                'latitude' => '24.9417890',
                'longitude' => '67.1628307',
                'area_size' => '250.00',
                'size_unit' => 'Sqy',
                'positioning' => 'North Open',
                'front_face' => 'Apartment',
                'back_site' => 'Park',
                'demand_price' => '18000.00',
                'pricetype' => 'Own Price',
                'housetype' => 'Single',
                'floor' => NULL,
                'bedrooms' => '4',
                'consage' => NULL,
                'conscond' => NULL,
                'postas' => 'Individual',
                'social' => 'Y',
                'user_id' => 1,
                'created_at' => '2025-10-02 00:02:43',
                'updated_at' => '2025-10-02 00:02:43',
            ),
            2 => 
            array (
                'id' => 55,
                'city_id' => 1,
                'town_id' => 3,
                'sector_id' => 28,
                'block_id' => NULL,
                'purpose' => 'Rent',
                'category' => 'Residential',
                'proptype' => 'Home',
                'featured' => 0,
                'title' => '120 Sqft Luxary Home',
                'description' => 'Best Location, Gated Community',
                'address' => 'Gulistan e Johar Blk 7, Safoora',
                'latitude' => '24.9392926',
                'longitude' => '67.1624279',
                'area_size' => '120.00',
                'size_unit' => 'Sqf',
                'positioning' => 'East Open',
                'front_face' => 'Main Road',
                'back_site' => 'Mosque',
                'demand_price' => '12000.00',
                'pricetype' => 'Total Price',
                'housetype' => 'Single',
                'floor' => NULL,
                'bedrooms' => '3',
                'consage' => 'New',
                'conscond' => 'Normal',
                'postas' => 'Individual',
                'social' => 'Y',
                'user_id' => 1,
                'created_at' => '2025-10-07 23:15:58',
                'updated_at' => '2025-10-07 23:15:58',
            ),
            3 => 
            array (
                'id' => 56,
                'city_id' => 1,
                'town_id' => 2,
                'sector_id' => NULL,
                'block_id' => NULL,
                'purpose' => 'Sale',
                'category' => 'Residential',
                'proptype' => 'Cottage',
                'featured' => 1,
                'title' => '150 Yards Cottage, Part  view',
                'description' => 'Road Facing, Good Location',
                'address' => 'Blk-7, Safoora, Gulzar Hijri',
                'latitude' => '24.9437482',
                'longitude' => '67.1487164',
                'area_size' => '150.00',
                'size_unit' => 'Sqy',
                'positioning' => 'East Open',
                'front_face' => 'Mosque',
                'back_site' => 'Jinnah Avenue',
                'demand_price' => '200000.00',
                'pricetype' => 'Own Price',
                'housetype' => 'Single',
                'floor' => '2nd',
                'bedrooms' => '4',
                'consage' => 'New',
                'conscond' => 'Demolish',
                'postas' => 'Individual',
                'social' => 'Y',
                'user_id' => 1,
                'created_at' => '2025-10-07 23:20:32',
                'updated_at' => '2025-10-07 23:20:32',
            ),
            4 => 
            array (
                'id' => 57,
                'city_id' => 1,
                'town_id' => 3,
                'sector_id' => 28,
                'block_id' => 168,
                'purpose' => 'Rent',
                'category' => 'Residential',
                'proptype' => 'Apartment',
                'featured' => 0,
                'title' => '240 Sqft Prime Location',
                'description' => 'Best Value for Money',
                'address' => 'Sunlay Apartments Safoora',
                'latitude' => '24.9445848',
                'longitude' => '67.1662045',
                'area_size' => '240.00',
                'size_unit' => 'Sqf',
                'positioning' => 'West Open',
                'front_face' => 'Homes',
                'back_site' => 'Compound',
                'demand_price' => '25000.00',
                'pricetype' => 'Booking Price',
                'housetype' => 'Single',
                'floor' => '2nd',
                'bedrooms' => '3',
                'consage' => 'New',
                'conscond' => 'Renovated',
                'postas' => 'Individual',
                'social' => 'Y',
                'user_id' => 1,
                'created_at' => '2025-10-07 23:22:43',
                'updated_at' => '2025-10-07 23:22:43',
            ),
            5 => 
            array (
                'id' => 58,
                'city_id' => 1,
                'town_id' => 2,
                'sector_id' => NULL,
                'block_id' => NULL,
                'purpose' => 'Sale',
                'category' => 'Residential',
                'proptype' => 'Home',
                'featured' => 0,
                'title' => '80 Yards Home',
                'description' => 'New Location, Park Facing',
                'address' => 'Saima Presidency',
                'latitude' => '24.9414718',
                'longitude' => '67.1569347',
                'area_size' => '80.00',
                'size_unit' => 'Sqy',
                'positioning' => 'North Open',
                'front_face' => 'Park',
                'back_site' => 'Park',
                'demand_price' => '9800.00',
                'pricetype' => 'Own Price',
                'housetype' => 'Single',
                'floor' => NULL,
                'bedrooms' => '2',
                'consage' => 'New',
                'conscond' => 'Demolish',
                'postas' => 'Individual',
                'social' => 'Y',
                'user_id' => 1,
                'created_at' => '2025-10-07 23:24:23',
                'updated_at' => '2025-10-07 23:24:23',
            ),
        ));
        
        
    }
}